# Generated by Django 4.0.2 on 2022-02-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='피드 생성일'),
        ),
    ]
