# Generated by Django 4.0.2 on 2022-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_artist_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='출생년도'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='패스워드'),
        ),
    ]
