# Generated by Django 4.0.2 on 2022-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='albumImg',
            field=models.ImageField(default='/static/img/default.jpeg', upload_to='albumImg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일 주소'),
        ),
    ]
