# Generated by Django 4.0.2 on 2022-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_certification_albumimg_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='albumImg',
            field=models.ImageField(blank=True, default='../static/img/default.jpeg', upload_to='albumImg'),
        ),
    ]
