# Generated by Django 4.0.2 on 2022-02-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_certification_albumimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='albumImg',
            field=models.ImageField(blank=True, null=True, upload_to='albumImg'),
        ),
    ]
