# Generated by Django 4.0.2 on 2022-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_certification_albumimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
